const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('ws2', {
  pickFile: () => ipcRenderer.invoke('pick-file'),
  classifyFile: (abs) => ipcRenderer.invoke('classify-file', abs),
  fileUrlAbs: (abs) => ipcRenderer.invoke('file-url-abs', abs),
  openExternalAbs: (abs) => ipcRenderer.invoke('open-external-abs', abs),
  pathExists: (abs) => ipcRenderer.invoke('path-exists', abs),
  readDoc: (p) => ipcRenderer.invoke('read-doc', p),
  pathInfo: (p) => ipcRenderer.invoke('path-info', p),
  appVersion: () => ipcRenderer.invoke('app-version'),
  saveDoc: (p, c) => ipcRenderer.invoke('save-doc', p, c),
  exportPdf: (p, mode, html) => ipcRenderer.invoke('export-pdf', p, mode, html),
  recents: () => ipcRenderer.invoke('recents-list'),
  recentsAdd: (p) => ipcRenderer.invoke('recents-add', p),
  historyList: (p) => ipcRenderer.invoke('history-list', p),
  historyRead: (p, id) => ipcRenderer.invoke('history-read', p, id),
  setDirty: (v) => ipcRenderer.send('set-dirty', v),
  winClose: () => ipcRenderer.send('win-close'), // Cmd+W 空态：关窗口（主进程按平台分流：macOS 隐藏驻留/其他退出）
  watchDoc: (p) => ipcRenderer.send('watch-doc', p),
  unwatchDoc: () => ipcRenderer.send('unwatch-doc'),
  onDocChanged: (cb) => ipcRenderer.on('doc-changed', (_e, p) => cb(p)),
  onWsTreeChanged: (cb) => ipcRenderer.on('ws-tree-changed', () => cb()),
  onOpenFile: (cb) => ipcRenderer.on('open-file', (_e, p) => cb(p)),
  onMenu: (cb) => ipcRenderer.on('menu', (_e, cmd) => cb(cmd)),

  // 本地文件夹工作区 (F06)
  pickFolder: () => ipcRenderer.invoke('pick-folder'),
  wsGetRoot: () => ipcRenderer.invoke('ws-get-root'),
  wsReadTree: () => ipcRenderer.invoke('ws-read-tree'),
  wsNewDoc: (dirRel, base, html) => ipcRenderer.invoke('ws-new-doc', dirRel, base, html),
  wsSaveDocAs: (base, html, ext, opts) => ipcRenderer.invoke('ws-save-doc-as', base, html, ext, opts), // ext 'md'=写盘前转 md；opts.reveal=导出语义 Finder 高亮
  wsMakeDir: (dirRel, name) => ipcRenderer.invoke('ws-make-dir', dirRel, name),
  wsRename: (relPath, newLeaf) => ipcRenderer.invoke('ws-rename', relPath, newLeaf),
  wsMove: (relPath, destDirRel) => ipcRenderer.invoke('ws-move', relPath, destDirRel),
  wsDelete: (relPath) => ipcRenderer.invoke('ws-delete', relPath),
  wsUndoDelete: (token) => ipcRenderer.invoke('ws-undo-delete', token),
  wsOpenExternal: (relPath) => ipcRenderer.invoke('ws-open-external', relPath),
  wsFileUrl: (relPath) => ipcRenderer.invoke('ws-file-url', relPath),
  wsGetTabs: () => ipcRenderer.invoke('ws-get-tabs'),
  wsSetTabs: (state, root) => ipcRenderer.invoke('ws-set-tabs', state, root),
  wsGetWebTabs: () => ipcRenderer.invoke('ws-get-web-tabs'), // 全局网页标签(跟工作区无关):{entries, activeKey}
  wsSetWebTabs: (entries, activeKey) => ipcRenderer.invoke('ws-set-web-tabs', entries, activeKey),
  wsTemplates: () => ipcRenderer.invoke('ws-templates'),
  aiGuide: () => ipcRenderer.invoke('ai-guide'),

  // 网页标签（浏览器）——view 活在主进程,renderer 只发指令 + 收状态镜像（U3）
  webNavigate: (key, input) => ipcRenderer.invoke('web-navigate', key, input),
  webLoad: (key, url) => ipcRenderer.invoke('web-load', key, url),
  webPdf: (key) => ipcRenderer.invoke('web-pdf', key),
  webShow: (key, bounds) => ipcRenderer.send('web-show', key, bounds),
  webHide: (key) => ipcRenderer.send('web-hide', key),
  webSetBounds: (key, bounds) => ipcRenderer.send('web-set-bounds', key, bounds),
  webSetVisible: (key, visible) => ipcRenderer.send('web-set-visible', key, visible),
  webClose: (key) => ipcRenderer.send('web-close', key),
  webDestroyAll: () => ipcRenderer.send('web-destroy-all'),
  webNav: (key, action) => ipcRenderer.send('web-nav', key, action),
  webFind: (key, text, opts) => ipcRenderer.send('web-find', key, text, opts),
  webStopFind: (key, action) => ipcRenderer.send('web-stop-find', key, action),
  webFocusChrome: () => ipcRenderer.send('web-focus-chrome'),
  wsRevealPath: (p) => ipcRenderer.send('ws-reveal-path', p),
  onWebTabUpdated: (cb) => ipcRenderer.on('web-tab-updated', (_e, s) => cb(s)),
  onWebOpenRequest: (cb) => ipcRenderer.on('web-open-request', (_e, r) => cb(r)),
  onWebFound: (cb) => ipcRenderer.on('web-found', (_e, r) => cb(r)),
  onWebDownload: (cb) => ipcRenderer.on('web-download', (_e, r) => cb(r)),
  onWebRebound: (cb) => ipcRenderer.on('web-rebound', () => cb()) // 唤回后主进程要 renderer 重发 view bounds
});
